// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZgEEw68JfmtC6kpW0rlgJWivQMoAE6Q',
    appId: '1:953718252250:web:bbbe8ab4046ad75f3bbbe3',
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    authDomain: 'furever-23375.firebaseapp.com',
    storageBucket: 'furever-23375.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChaYcUdeQo3Mj9CtJKOBmxfOSVdxbKR1A',
    appId: '1:953718252250:android:38fc6d5a70ffeaa53bbbe3',
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    storageBucket: 'furever-23375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6abOoPjEp7FUtLu0LG7xV31GQCFiebGU',
    appId: '1:953718252250:ios:61f6d5076a846df03bbbe3',
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    storageBucket: 'furever-23375.firebasestorage.app',
    iosBundleId: 'com.example.furever',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6abOoPjEp7FUtLu0LG7xV31GQCFiebGU',
    appId: '1:953718252250:ios:61f6d5076a846df03bbbe3',
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    storageBucket: 'furever-23375.firebasestorage.app',
    iosBundleId: 'com.example.furever',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCZgEEw68JfmtC6kpW0rlgJWivQMoAE6Q',
    appId: '1:953718252250:web:954292e3550375fb3bbbe3',
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    authDomain: 'furever-23375.firebaseapp.com',
    storageBucket: 'furever-23375.firebasestorage.app',
  );
}
