// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB']!,
    appId: dotenv.env['FIREBASE_API_ID_WEB']!,
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    authDomain: 'furever-23375.firebaseapp.com',
    storageBucket: 'furever-23375.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
    appId: dotenv.env['FIREBASE_API_ID_ANDROID']!,
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    storageBucket: 'furever-23375.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: dotenv.env['FIREBASE_API_ID_IOS']!,
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    storageBucket: 'furever-23375.firebasestorage.app',
    iosBundleId: 'com.example.furever',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MAC']!,
    appId: dotenv.env['FIREBASE_API_ID_MAC']!,
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    storageBucket: 'furever-23375.firebasestorage.app',
    iosBundleId: 'com.example.furever',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WIN']!,
    appId: dotenv.env['FIREBASE_API_ID_WIN']!,
    messagingSenderId: '953718252250',
    projectId: 'furever-23375',
    authDomain: 'furever-23375.firebaseapp.com',
    storageBucket: 'furever-23375.firebasestorage.app',
  );
}
